GET http://localhost:3000/test/Pelle

###

GET http://localhost:3000/todo/68f7216c-b9ca-496d-9850-c746459c8812


###


GET http://localhost:3000/todo/


###

POST http://localhost:3000/todo
Content-Type: application/json

{
    "todo": "Användarhantering",
    "user": "68f7216c-b9ca-496d-9850-c746459c88"
}

###

POST http://localhost:3000/todo/done
Content-Type: application/json

{
    "id": 1
}

###
// SKAPA NY ANVÄNDARE
POST https://coral-app-k4emb.ondigitalocean.app/user
Content-Type: application/json

{
    "email": "kalle@mail.com",
    "password": "ruben"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "janne@test.com",
    "password": "test"
}

###


GET http://localhost:3000/user/?apikey=123456&email=janne@admin.com


###